# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Artifactvalidator < Formula
  desc "Validate forensic artifact definition files."
  homepage "https://github.com/forensicanalysis/artifactlib"
  version "0.16.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/forensicanalysis/artifactlib/releases/download/v0.16.1/artifactvalidator_0.16.1_macOS_arm64.tar.gz"
      sha256 "e9f44e278a51ceb3daaf8dd8302d0219d7a0fe544f24f50230810715f0a1996b"

      def install
        bin.install "artifactvalidator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forensicanalysis/artifactlib/releases/download/v0.16.1/artifactvalidator_0.16.1_macOS_amd64.tar.gz"
      sha256 "c7575122c5bad5c79bf2ba25703adf4d70cdd205a50121ab567d82d86aa693ce"

      def install
        bin.install "artifactvalidator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/forensicanalysis/artifactlib/releases/download/v0.16.1/artifactvalidator_0.16.1_Linux_amd64.tar.gz"
      sha256 "25d4326e22f77029dd1f65c55faf826dbb91239a845ecf99810ff6129af5c38c"

      def install
        bin.install "artifactvalidator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forensicanalysis/artifactlib/releases/download/v0.16.1/artifactvalidator_0.16.1_Linux_arm64.tar.gz"
      sha256 "ae3b93754911074050ef115cfa24a1e4183980db0d10b12da60273cec9444949"

      def install
        bin.install "artifactvalidator"
      end
    end
  end
end
