# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fs < Formula
  desc "A recursive file system viewer."
  homepage "https://github.com/forensicanalysis/recursivefs"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/forensicanalysis/recursivefs/releases/download/v0.2.0/fs_0.2.0_macOS_amd64.tar.gz"
    sha256 "014eacdc652b1f64e1a33c249b7c99e47dc9b52c7332bd679c6a1f378445ff49"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/forensicanalysis/recursivefs/releases/download/v0.2.0/fs_0.2.0_macOS_arm64.tar.gz"
    sha256 "992a0c3fe60469836930d473b110cf820ff9cd2bed0e74a71080f6b5b42e8677"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/forensicanalysis/recursivefs/releases/download/v0.2.0/fs_0.2.0_Linux_amd64.tar.gz"
    sha256 "cd39747b778febdeb926ba791b75bcdd6cefe289248fd14ca2333779e44eb117"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/forensicanalysis/recursivefs/releases/download/v0.2.0/fs_0.2.0_Linux_arm64.tar.gz"
    sha256 "0e9e9883c0a550f231ede22468301556ac4330dcdb6c3131e36c7a825a58f87a"
  end

  def install
    bin.install "fs"
  end
end
