# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regffs < Formula
  desc "A Windows registry file (regf) viewer."
  homepage "https://github.com/forensicanalysis/regffs"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/forensicanalysis/regffs/releases/download/v0.1.1/regffs_0.1.1_macOS_arm64.tar.gz"
      sha256 "d84056a5e2b29cb9f08ddb028d98388b0ef7e75d756ba5ba3afebf6706557193"

      def install
        bin.install "regffs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forensicanalysis/regffs/releases/download/v0.1.1/regffs_0.1.1_macOS_amd64.tar.gz"
      sha256 "73e19bbaa9b73421ed7756131ab78699df6515d2a9fa87d837d2a4dae13f66f5"

      def install
        bin.install "regffs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/forensicanalysis/regffs/releases/download/v0.1.1/regffs_0.1.1_Linux_amd64.tar.gz"
      sha256 "97b556dd137e4bb756ff7e536459012feb72c98182b9651f3e15a72655a3fa40"

      def install
        bin.install "regffs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forensicanalysis/regffs/releases/download/v0.1.1/regffs_0.1.1_Linux_arm64.tar.gz"
      sha256 "4397f254a710319bfb63f8d30cdd80f935148c21b9d059507ce6848cdb294492"

      def install
        bin.install "regffs"
      end
    end
  end
end
